(()=>{
'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const mix=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const prv=(i,n)=>(i+n-1)%n,nxt=(i,n)=>(i+1)%n;
const feedback=(el,ok,t)=>{el.className='feedback show '+(ok?'ok':'no');el.textContent=t};
const options=(el,vals,key,fn)=>{el.innerHTML=mix(vals).map(v=>`<button class="choice" data-${key}="${v}">${v}</button>`).join('');$$(`[data-${key}]`).forEach(b=>b.onclick=()=>fn(b))};
const mark=(key,ans,b,ok)=>{$$(`[data-${key}]`).forEach(x=>x.disabled=true);b.classList.add(ok?'correct':'wrong');const c=$$(`[data-${key}]`).find(x=>x.dataset[key]===ans);if(c)c.classList.add('correct')};

const sections=[['home','홈','⌂'],['pos','품사','1'],['skeleton','기본 구조','2'],['components','문장 성분','3'],['structure','홑·겹문장','4'],['connected','이어진문장','5'],['embedded','안은문장','6'],['intention','표현 의도','7'],['game','땅따먹기','★']];
const state={teacher:false,done:new Set(JSON.parse(localStorage.getItem('sentenceLabDoneV2')||'[]'))};
const save=()=>localStorage.setItem('sentenceLabDoneV2',JSON.stringify([...state.done]));
function progress(){const p=Math.round(state.done.size/(sections.length-1)*100);$('#progressText').textContent=p+'%';$('#progressFill').style.width=p+'%'}
function go(id){$$('.section').forEach(x=>x.classList.toggle('active',x.dataset.section===id));$$('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));if(id!=='home'){state.done.add(id);save();progress()}window.scrollTo({top:0,behavior:'smooth'})}
$('#sideNav').innerHTML=sections.map(([id,l,n])=>`<button class="nav-btn ${id==='home'?'active':''}" data-nav="${id}"><span class="nav-num">${n}</span>${l}</button>`).join('');
$('#mobileNav').innerHTML=sections.map(([id,l])=>`<button class="mnav ${id==='home'?'active':''}" data-nav="${id}">${l}</button>`).join('');$$('[data-nav]').forEach(b=>b.onclick=()=>go(b.dataset.nav));
const modules=[['pos','🧩','1. 품사 복습','9품사와 품사·문장 성분의 차이를 확인합니다.'],['skeleton','🦴','2. 문장의 기본 구조','서술어를 중심으로 세 가지 기본 구조를 봅니다.'],['components','🧱','3. 문장 성분','주성분·부속 성분·독립 성분을 실제 문장에서 분석합니다.'],['structure','🔍','4. 홑문장과 겹문장','주어·서술어 관계의 횟수를 확인합니다.'],['connected','🔗','5. 이어진문장','대등·종속 관계를 구분하고 직접 문장을 만듭니다.'],['embedded','🪆','6. 안은문장','다섯 가지 안긴문장과 전성 어미를 확인합니다.'],['intention','🎯','7. 표현 의도','같은 내용을 의도에 맞는 짜임으로 표현합니다.'],['game','🗺️','정리. 땅따먹기','배운 내용을 게임으로 정리합니다.']];
$('#moduleGrid').innerHTML=modules.map(m=>`<button class="module-card" data-go="${m[0]}"><div class="icon">${m[1]}</div><h3>${m[2]}</h3><p>${m[3]}</p><div class="open">열기 →</div></button>`).join('');$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));progress();
$('#teacherModeBtn').onclick=()=>{state.teacher=!state.teacher;document.body.classList.toggle('teacher-mode',state.teacher);$('#teacherModeBtn').classList.toggle('active',state.teacher);$('#teacherModeBtn').textContent=state.teacher?'교사 모드 ON':'교사 모드'};
$('#resetBtn').onclick=()=>{if(confirm('학습 진행 기록을 초기화할까요?')){state.done.clear();save();progress()}};

function simpleQuiz(cfg){let i=0,qs=mix(cfg.qs);function draw(){const q=qs[i];$(cfg.count).textContent=`${i+1} / ${qs.length}`;$(cfg.prompt).textContent=q.s||q.w;const h=$(cfg.hint);if(h)h.textContent=q.h||'';$(cfg.fb).className='feedback';options($(cfg.choices),cfg.opts||q.choices,cfg.key,b=>{const v=b.dataset[cfg.key],ok=v===q.a;mark(cfg.key,q.a,b,ok);feedback($(cfg.fb),ok,ok?(q.ok||'정답입니다.'):(q.no||`정답은 ${q.a}입니다.`)+(q.why?' '+q.why:''))})}$(cfg.prev).onclick=()=>{i=prv(i,qs.length);draw()};$(cfg.next).onclick=()=>{i=nxt(i,qs.length);draw()};draw();return()=>qs[i]}

simpleQuiz({key:'pos',count:'#posCount',prompt:'#posWord',hint:'#posHint',choices:'#posChoices',fb:'#posFeedback',prev:'#posPrev',next:'#posNext',opts:['명사','대명사','수사','동사','형용사','관형사','부사','조사','감탄사'],qs:[{w:'책',h:'사물의 이름을 나타냄',a:'명사'},{w:'우리',h:'사람이나 사물을 대신 가리킴',a:'대명사'},{w:'둘째',h:'수량이나 순서를 나타냄',a:'수사'},{w:'웃다',h:'움직임을 나타내며 형태가 변함',a:'동사'},{w:'맑다',h:'상태나 성질을 나타내며 형태가 변함',a:'형용사'},{w:'새',h:'체언 앞에서 체언을 꾸밈',a:'관형사'},{w:'아주',h:'주로 용언을 꾸밈',a:'부사'},{w:'을/를',h:'다른 말과의 관계를 나타냄',a:'조사'},{w:'어머',h:'감정·부름·응답 등을 독립적으로 나타냄',a:'감탄사'}]});

const ex=[['꽃이 예쁘다.','예쁘다','형용사','서술어'],['예쁜 꽃이 피었다.','예쁜','형용사','관형어'],['꽃이 예쁘게 피었다.','예쁘게','형용사','부사어'],['동생이 새 옷을 입었다.','새','관형사','관형어']];$('#identityExamples').innerHTML=ex.map(e=>`<div class="example-item"><strong>${e[0]}</strong><small>‘${e[1]}’ → 품사 ${e[2]} / 성분 ${e[3]}</small></div>`).join('');
let idi=0,idp=null,idc=null,idqs=mix([{s:'동생이 새 옷을 입었다.',t:'새',p:'관형사',c:'관형어'},{s:'예쁜 꽃이 피었다.',t:'예쁜',p:'형용사',c:'관형어'},{s:'꽃이 예쁘다.',t:'예쁘다',p:'형용사',c:'서술어'},{s:'꽃이 예쁘게 피었다.',t:'예쁘게',p:'형용사',c:'부사어'},{s:'경식아, 저 강아지 정말 귀엽다.',t:'경식아',p:'명사+조사',c:'독립어'}]);
function drawId(){const q=idqs[idi];idp=idc=null;$('#idCount').textContent=`${idi+1} / ${idqs.length}`;$('#idSentence').innerHTML=q.s.replace(q.t,`<mark>${q.t}</mark>`);$('#idTarget').textContent=`‘${q.t}’의 품사와 문장 성분을 각각 고르세요.`;$('#idFeedback').className='feedback';options($('#idPosChoices'),['관형사','형용사','명사+조사','부사'],'idp',b=>{$$('[data-idp]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');idp=b.dataset.idp});options($('#idCompChoices'),['관형어','서술어','부사어','독립어'],'idc',b=>{$$('[data-idc]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');idc=b.dataset.idc})}
$('#idCheck').onclick=()=>{const q=idqs[idi];if(!idp||!idc)return feedback($('#idFeedback'),false,'두 항목을 모두 골라 주세요.');const ok=idp===q.p&&idc===q.c;feedback($('#idFeedback'),ok,ok?'정답입니다. 품사는 단어의 갈래, 문장 성분은 문장 안의 역할입니다.':`정답은 품사 ${q.p}, 문장 성분 ${q.c}입니다.`)};$('#idPrev').onclick=()=>{idi=prv(idi,idqs.length);drawId()};$('#idNext').onclick=()=>{idi=nxt(idi,idqs.length);drawId()};drawId();

simpleQuiz({key:'sk',count:'#skCount',prompt:'#skSentence',choices:'#skChoices',fb:'#skFeedback',prev:'#skPrev',next:'#skNext',opts:['어찌하다','어떠하다','무엇이다'],qs:[{s:'꽃이 피었다.',a:'어찌하다'},{s:'밤바람이 차갑다.',a:'어떠하다'},{s:'나는 중학생이다.',a:'무엇이다'},{s:'새가 모이를 먹는다.',a:'어찌하다'},{s:'새 학교는 정말 낯설다.',a:'어떠하다'},{s:'철수는 의사이다.',a:'무엇이다'}]});

const compQs=mix([{s:'선호가 숙제를 끝냈다.',t:[['선호가','주어'],['숙제를','목적어'],['끝냈다','서술어']]},{s:'소미가 회장이 되었다.',t:[['소미가','주어'],['회장이','보어'],['되었다','서술어']]},{s:'진우는 막내가 아니다.',t:[['진우는','주어'],['막내가','보어'],['아니다','서술어']]},{s:'찬미가 새 모자를 썼다.',t:[['찬미가','주어'],['새','관형어'],['모자를','목적어'],['썼다','서술어']]},{s:'개미가 먹이를 부지런히 나른다.',t:[['개미가','주어'],['먹이를','목적어'],['부지런히','부사어'],['나른다','서술어']]},{s:'지영아, 너는 피아노를 정말 잘 치는구나.',t:[['지영아,','독립어'],['너는','주어'],['피아노를','목적어'],['정말','부사어'],['잘','부사어'],['치는구나','서술어']]},{s:'나는 할머니께 새 신발을 사드렸다.',t:[['나는','주어'],['할머니께','부사어'],['새','관형어'],['신발을','목적어'],['사드렸다','서술어']]}]);
const labels=['주어','서술어','목적어','보어','관형어','부사어','독립어'],tc={주어:'subject',서술어:'predicate',목적어:'object',보어:'complement',관형어:'adnominal',부사어:'adverbial',독립어:'independent'};let ci=0,active=null,assigned=[];
function drawComp(){const q=compQs[ci];active=null;assigned=Array(q.t.length).fill(null);$('#compCount').textContent=`${ci+1} / ${compQs.length}`;$('#compSentence').textContent=q.s;$('#compFeedback').className='feedback';$('#compTokens').innerHTML=q.t.map((x,i)=>`<button class="token" data-ti="${i}">${x[0]}<div class="tag" id="tag${i}">미지정</div></button>`).join('');$$('[data-ti]').forEach(b=>b.onclick=()=>{$$('[data-ti]').forEach(x=>x.classList.remove('tagged'));b.classList.add('tagged');active=+b.dataset.ti});options($('#compLabels'),labels,'cl',b=>{if(active===null)return feedback($('#compFeedback'),false,'먼저 어절을 하나 선택하세요.');assigned[active]=b.dataset.cl;const t=$(`#tag${active}`);t.textContent=b.dataset.cl;t.className='tag '+tc[b.dataset.cl]})}
$('#compCheck').onclick=()=>{const q=compQs[ci];if(assigned.some(x=>!x))return feedback($('#compFeedback'),false,'아직 지정하지 않은 어절이 있습니다.');const n=assigned.filter((x,i)=>x!==q.t[i][1]).length;feedback($('#compFeedback'),!n,n?`${n}개를 다시 확인해 보세요. 서술어부터 찾으면 쉽습니다.`:'모두 맞았습니다.')};$('#compReveal').onclick=()=>{compQs[ci].t.forEach((x,i)=>{assigned[i]=x[1];const t=$(`#tag${i}`);t.textContent=x[1];t.className='tag '+tc[x[1]]});feedback($('#compFeedback'),true,'정답을 표시했습니다.')};$('#compPrev').onclick=()=>{ci=prv(ci,compQs.length);drawComp()};$('#compNext').onclick=()=>{ci=nxt(ci,compQs.length);drawComp()};drawComp();

let di=0,dqs=mix([{s:'작은 물고기가 물속에서 빠르게 헤엄쳤다.',t:'작은',a:'성립한다',w:'관형어를 빼도 “물고기가 헤엄쳤다.”가 성립합니다.'},{s:'작은 물고기가 물속에서 빠르게 헤엄쳤다.',t:'물고기가',a:'성립하지 않는다',w:'주어가 빠지면 기본 관계를 확인하기 어렵습니다.'},{s:'부지런한 학생이 열심히 공부했다.',t:'열심히',a:'성립한다',w:'부사어를 빼도 “학생이 공부했다.”가 성립합니다.'},{s:'맛있는 음식이 식탁에 가득 놓였다.',t:'놓였다',a:'성립하지 않는다',w:'서술어가 빠지면 문장이 완결되지 않습니다.'},{s:'밝은 달이 밤하늘에 환하게 빛났다.',t:'밝은',a:'성립한다',w:'관형어를 빼도 “달이 빛났다.”가 성립합니다.'}]);
function drawDel(){const q=dqs[di];$('#delCount').textContent=`${di+1} / ${dqs.length}`;$('#delSentence').innerHTML=q.s.replace(q.t,`<mark>${q.t}</mark>`);$('#delFeedback').className='feedback';options($('#delChoices'),['성립한다','성립하지 않는다'],'del',b=>{const ok=b.dataset.del===q.a;mark('del',q.a,b,ok);feedback($('#delFeedback'),ok,(ok?'정답입니다. ':`정답은 ${q.a}입니다. `)+q.w)})}$('#delPrev').onclick=()=>{di=prv(di,dqs.length);drawDel()};$('#delNext').onclick=()=>{di=nxt(di,dqs.length);drawDel()};drawDel();

const getSt=simpleQuiz({key:'st',count:'#stCount',prompt:'#stSentence',choices:'#stChoices',fb:'#stFeedback',prev:'#stPrev',next:'#stNext',opts:['홑문장','겹문장'],qs:[{s:'버스가 종점으로 달린다.',a:'홑문장',pairs:[['버스가','달린다']]},{s:'제비꽃은 정말 예쁘다.',a:'홑문장',pairs:[['제비꽃은','예쁘다']]},{s:'나는 동생이 어지른 방을 치웠다.',a:'겹문장',pairs:[['나는','치웠다'],['동생이','어지른']]},{s:'지아는 비가 그치기를 간절히 바랐다.',a:'겹문장',pairs:[['지아는','바랐다'],['비가','그치기']]},{s:'정우는 영화를 보고 희수는 책을 읽는다.',a:'겹문장',pairs:[['정우는','보고'],['희수는','읽는다']]}]});$('#stPairs').onclick=()=>{$('#pairLines').innerHTML=getSt().pairs.map((p,i)=>`<div class="pair-line"><strong>${i+1}번째 관계</strong><div class="pair-badges"><span class="badge s">주어 ${p[0]}</span><span class="badge p">서술어 ${p[1]}</span></div></div>`).join('')};

simpleQuiz({key:'cn',count:'#cnCount',prompt:'#cnSentence',hint:'#cnHint',choices:'#cnChoices',fb:'#cnFeedback',prev:'#cnPrev',next:'#cnNext',opts:['대등하게 이어진문장','종속적으로 이어진문장'],qs:[{s:'시아는 그림을 그리고 찬호는 글을 쓴다.',a:'대등하게 이어진문장',h:'두 사실을 나란히 제시합니다.'},{s:'공원에 놀이기구가 많아서 동생의 기분이 좋다.',a:'종속적으로 이어진문장',h:'앞 절이 뒤 절의 원인입니다.'},{s:'나는 상한 음식을 먹고 배탈이 났다.',a:'종속적으로 이어진문장',h:'‘-고’가 쓰였지만 사건이 계기적으로 이어집니다.'},{s:'윤지는 웃었지만 민서는 울었다.',a:'대등하게 이어진문장',h:'두 사실이 대조됩니다.'},{s:'산이 높으면 골짜기가 깊다.',a:'종속적으로 이어진문장',h:'앞 절은 뒤 절의 조건입니다.'}]});

let bi=0,bqs=mix([{a:'시아는 그림을 그린다.',b:'찬호는 글을 쓴다.',z:'시아는 그림을 그리고 찬호는 글을 쓴다.',c:['시아는 그림을 그리고 찬호는 글을 쓴다.','시아는 그림을 그려서 찬호는 글을 쓴다.','시아는 그림을 그리면 찬호는 글을 쓴다.'],w:'두 사실을 나란히 제시하므로 ‘-고’가 자연스럽습니다.'},{a:'공원에 놀이기구가 많다.',b:'동생의 기분이 좋다.',z:'공원에 놀이기구가 많아서 동생의 기분이 좋다.',c:['공원에 놀이기구가 많아서 동생의 기분이 좋다.','공원에 놀이기구가 많지만 동생의 기분이 좋다.','공원에 놀이기구가 많거나 동생의 기분이 좋다.'],w:'놀이기구가 많은 것이 기분이 좋은 원인입니다.'},{a:'비가 온다.',b:'땅이 질다.',z:'비가 와서 땅이 질다.',c:['비가 와서 땅이 질다.','비가 오지만 땅이 질다.','비가 오거나 땅이 질다.'],w:'비가 오는 것이 땅이 진 원인입니다.'},{a:'동생은 운동을 한다.',b:'동생은 일찍 일어난다.',z:'동생은 운동을 하려고 일찍 일어난다.',c:['동생은 운동을 하려고 일찍 일어난다.','동생은 운동을 하지만 일찍 일어난다.','동생은 운동을 하거나 일찍 일어난다.'],w:'일찍 일어나는 목적이 운동입니다.'}]);
function drawBuild(){const q=bqs[bi];$('#cbCount').textContent=`${bi+1} / ${bqs.length}`;$('#cbA').textContent=q.a;$('#cbB').textContent=q.b;$('#cbFeedback').className='feedback';options($('#cbChoices'),q.c,'cb',b=>{const ok=b.dataset.cb===q.z;mark('cb',q.z,b,ok);feedback($('#cbFeedback'),ok,(ok?'자연스럽게 만들었습니다. ':`정답 예시는 “${q.z}”입니다. `)+q.w)})}$('#cbPrev').onclick=()=>{bi=prv(bi,bqs.length);drawBuild()};$('#cbNext').onclick=()=>{bi=nxt(bi,bqs.length);drawBuild()};drawBuild();

let ti=0,tqs=mix([{s:'아기가 울다.',f:'나는 ______ 소리를 들었다.',z:'아기가 우는',c:['아기가 우는','아기가 울기','아기가 울게'],w:'‘아기가 우는’이 ‘소리’를 꾸미므로 관형절입니다.'},{s:'농사가 잘되다.',f:'농부는 ______ 바란다.',z:'농사가 잘되기를',c:['농사가 잘되기를','농사가 잘되는','농사가 잘되게'],w:'‘농사가 잘되기’가 목적어 기능을 하므로 명사절입니다.'},{s:'땀이 나다.',f:'민후는 ______ 뛰었다.',z:'땀이 나게',c:['땀이 나게','땀이 나기','땀이 나는'],w:'‘땀이 나게’가 ‘뛰었다’를 꾸미므로 부사절입니다.'},{s:'은우가 노래를 부른다.',f:'수아는 ______ 모습을 보았다.',z:'은우가 노래를 부르는',c:['은우가 노래를 부르는','은우가 노래를 부르기','은우가 노래를 부르게'],w:'‘모습’을 꾸미므로 관형절입니다.'}]);
function drawTr(){const q=tqs[ti];$('#trCount').textContent=`${ti+1} / ${tqs.length}`;$('#trSource').textContent=q.s;$('#trFrame').textContent=q.f;$('#trFeedback').className='feedback';options($('#trChoices'),q.c,'tr',b=>{const ok=b.dataset.tr===q.z;mark('tr',q.z,b,ok);feedback($('#trFeedback'),ok,(ok?'잘 바꾸었습니다. ':`정답은 “${q.z}”입니다. `)+q.w)})}$('#trPrev').onclick=()=>{ti=prv(ti,tqs.length);drawTr()};$('#trNext').onclick=()=>{ti=nxt(ti,tqs.length);drawTr()};drawTr();

simpleQuiz({key:'em',count:'#emCount',prompt:'#emSentence',hint:'#emHint',choices:'#emChoices',fb:'#emFeedback',prev:'#emPrev',next:'#emNext',opts:['명사절','관형절','부사절','서술절','인용절'],qs:[{s:'나는 그가 오기를 기다렸다.',a:'명사절',h:'‘그가 오기’가 목적어 기능을 합니다.'},{s:'이것은 내가 읽은 소설책이다.',a:'관형절',h:'‘내가 읽은’이 ‘소설책’을 꾸밉니다.'},{s:'빙수는 이가 시리도록 차가웠다.',a:'부사절',h:'‘이가 시리도록’이 ‘차가웠다’를 꾸밉니다.'},{s:'토끼는 앞발이 짧다.',a:'서술절',h:'‘앞발이 짧다’가 전체 주어의 상태를 풀이합니다.'},{s:'진호는 “저도 이제 중학생이에요.”라고 말하였다.',a:'인용절',h:'다른 사람의 말을 절의 형식으로 안았습니다.'}]});

$$('[data-intent]').forEach(b=>b.onclick=()=>{const d=b.dataset.intent;feedback($('#intentFeedback'),true,d==='parallel'?'이어진문장: 두 사실을 비슷한 비중으로 나란히 제시하는 의도에 어울립니다.':'관형절을 가진 안은문장: “그 소설”이 어떤 소설인지 구체화하는 의도에 어울립니다.')});const mk='sentenceLabMission';$('#missionText').value=localStorage.getItem(mk)||'';$('#saveMission').onclick=()=>{localStorage.setItem(mk,$('#missionText').value);$('#missionSaved').textContent='저장됨';setTimeout(()=>$('#missionSaved').textContent='',1200)};

const gameQs=[{q:'‘새’의 품사는?',c:['관형사','관형어','형용사','부사'],a:'관형사'},{q:'“예쁜 꽃이 피었다.”에서 ‘예쁜’의 문장 성분은?',c:['관형어','관형사','서술어','부사어'],a:'관형어'},{q:'“물이 얼음이 되었다.”에서 ‘얼음이’의 문장 성분은?',c:['보어','목적어','주어','부사어'],a:'보어'},{q:'체언을 꾸며 주는 문장 성분은?',c:['관형어','부사어','독립어','목적어'],a:'관형어'},{q:'“시냇물이 깨끗하다.”의 기본 구조는?',c:['무엇이 어떠하다','무엇이 어찌하다','무엇이 무엇이다'],a:'무엇이 어떠하다'},{q:'주어와 서술어의 관계가 한 번 나타나는 문장은?',c:['홑문장','겹문장','안은문장'],a:'홑문장'},{q:'“나는 상한 음식을 먹고 배탈이 났다.”는?',c:['종속적으로 이어진문장','대등하게 이어진문장','홑문장'],a:'종속적으로 이어진문장'},{q:'“나는 그가 오기를 기다렸다.”의 안긴문장은?',c:['명사절','관형절','부사절'],a:'명사절'},{q:'“토끼는 앞발이 짧다.”의 안긴문장은?',c:['서술절','부사절','명사절'],a:'서술절'},{q:'직접 인용에서 인용한 말 뒤에 붙는 조사는?',c:['라고','고','부터'],a:'라고'},{q:'“비가 온다. 땅이 질다.”를 자연스럽게 이은 문장은?',c:['비가 와서 땅이 질다.','비가 오지만 땅이 질다.','비가 오거나 땅이 질다.'],a:'비가 와서 땅이 질다.'},{q:'“은우가 노래를 부른다.”를 관형절로 바꾼 것은?',c:['은우가 노래를 부르는','은우가 노래를 부르기','은우가 노래를 부르게'],a:'은우가 노래를 부르는'},{q:'“지영아, 너는 피아노를 잘 치는구나.”에서 ‘지영아’는?',c:['독립어','주어','관형어'],a:'독립어'},{q:'“해외에서 유명한 그 소설은 영화로 만들어졌다.”의 효과는?',c:['어떤 소설인지 구체화','두 사실 단순 나열','원인 표시'],a:'어떤 소설인지 구체화'}];
const specials=['한 번 더','꽝','한 번 더','꽝'];let game={turn:'A',a:0,b:0,cell:null},mq=null;const modal=$('#quizModal');
function gu(){scoreA.textContent=game.a;scoreB.textContent=game.b;teamA.classList.toggle('active',game.turn==='A');teamB.classList.toggle('active',game.turn==='B');turnText.textContent=`${game.turn}팀 차례입니다.`}function turn(){game.turn=game.turn==='A'?'B':'A';gu()}
function board(){let v=mix([...Array(20)].map((_,i)=>''+(i+1)).concat(specials));v.push('시작');$('#board').innerHTML=v.map(x=>`<button class="cell ${x==='시작'?'start':specials.includes(x)?'special':''}" data-v="${x}">${x}<span class="owner"></span></button>`).join('');$$('.cell').forEach(c=>c.onclick=()=>cell(c));gu()}
function cell(c){if(/claim|neutral|start/.test(c.className))return;const v=c.dataset.v;if(v==='한 번 더'){c.classList.add(game.turn==='A'?'claim-a':'claim-b');c.querySelector('.owner').textContent=game.turn+'팀';game.turn==='A'?game.a++:game.b++;gu();return alert(`${game.turn}팀 한 번 더!`)}if(v==='꽝'){c.classList.add('neutral');turn();return alert('꽝!')}game.cell=c;mq=gameQs[(+v-1)%gameQs.length];qType.textContent='문제';qTitle.textContent=`${game.turn}팀 문제`;qText.textContent=mq.q;qFeedback.className='feedback';options(qChoices,mq.c,'qc',b=>{const ok=b.dataset.qc===mq.a;mark('qc',mq.a,b,ok);feedback(qFeedback,ok,ok?'정답! 이 칸을 차지합니다.':`정답은 ‘${mq.a}’입니다.`);if(ok){c.classList.add(game.turn==='A'?'claim-a':'claim-b');c.querySelector('.owner').textContent=game.turn+'팀';game.turn==='A'?game.a++:game.b++}else c.classList.add('neutral');setTimeout(()=>{modal.classList.remove('show');turn()},800)});modal.classList.add('show')}
modalClose.onclick=()=>modal.classList.remove('show');qReveal.onclick=()=>feedback(qFeedback,true,`정답: ${mq?mq.a:''}`);modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};randomCell.onclick=()=>{const a=$$('.cell').filter(c=>!/claim|neutral|start/.test(c.className));if(a.length)cell(a[Math.floor(Math.random()*a.length)])};resetGame.onclick=()=>{game={turn:'A',a:0,b:0,cell:null};board()};board();document.addEventListener('keydown',e=>{if(e.key==='Escape')modal.classList.remove('show')});
})();
